### ISSUE TITLE
Chat stopps working in-game, console error included

### ISSUE THREAD

**Issue by Jakesta13** [chunkaligned/fabric-discord-integration#13]
Chat doesn't work with this mod installed on Minecraft server version 1.19.3 / Fabric API version 0.73.2+1.19.3

Other installed mods (Issue only occurs when this mod is enabled):
```
NoChatReports-FABRIC-1.19.3-v1.19.0
lithium-fabric-mc1.19.3-0.10.4
fabric-api-0.73.2+1.19.3
```
Console output:
```
13.02 19:14:24 [Server] Server thread/ERROR Chain link failed, continuing to next one
13.02 19:14:24 [Server] INFO java.lang.NoSuchMethodError: 'net.minecraft.class_2561 net.minecraft.class_7471.method_44125()'
13.02 19:14:24 [Server] INFO at net.minecraft.class_3324.handler$zza000$broadcast(class_3324.java:1005) ~[server-intermediary.jar:?]
13.02 19:14:24 [Server] INFO at net.minecraft.class_3324.method_43673(class_3324.java) ~[server-intermediary.jar:?]
13.02 19:14:24 [Server] INFO at net.minecraft.class_3244.method_44155(class_3244.java:1435) ~[server-intermediary.jar:?]
13.02 19:14:24 [Server] INFO at net.minecraft.class_3244.method_45064(class_3244.java:1309) ~[server-intermediary.jar:?]
13.02 19:14:24 [Server] INFO at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
13.02 19:14:24 [Server] INFO at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
13.02 19:14:24 [Server] INFO at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
13.02 19:14:24 [Server] INFO at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
13.02 19:14:24 [Server] INFO at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
13.02 19:14:24 [Server] INFO at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:787) ~[server-intermediary.jar:?]
13.02 19:14:24 [Server] INFO at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:166) ~[server-intermediary.jar:?]
13.02 19:14:24 [Server] INFO at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
13.02 19:14:24 [Server] INFO at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:769) ~[server-intermediary.jar:?]
13.02 19:14:24 [Server] INFO at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:763) ~[server-intermediary.jar:?]
13.02 19:14:24 [Server] INFO at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
13.02 19:14:24 [Server] INFO at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748) ~[server-intermediary.jar:?]
13.02 19:14:24 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:680) ~[server-intermediary.jar:?]
13.02 19:14:24 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?]
13.02 19:14:24 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by hkva** [comment]
I'm having trouble reproducing this. Is this error occurring when you send an in-game message or when you send a Discord message?

![image](https://user-images.githubusercontent.com/91440203/218633779-a034ea13-816a-4da4-bd38-1c6115343b72.png)

**Comment by hkva** [comment]
It looks like there was an ABI break in one of the recent Fabric API versions... I bumped the dependencies and published a new release.

@Jakesta13 please try the latest release and see if that fixes your issue: https://github.com/chunkaligned/fabric-discord-integration/releases/tag/v1.2.2

**Comment by Jakesta13** [comment]
> It looks like there was an ABI break in one of the recent Fabric API versions... I bumped the dependencies and published a new release.
> 
> @Jakesta13 please try the latest release and see if that fixes your issue: https://github.com/chunkaligned/fabric-discord-integration/releases/tag/v1.2.2

Hey, I wasn't able to test it for a bit there but it's giving a different error now and preventing startup.
This might be apart of my Bot that I have set up, but I'm not able to check this out too much as I'm currently away from home for the next day and a bit.

I use this bot with another project that had broke(Which I tried switching to this mod to replace), but got that project working since my issue report, so I'm not sure why this mod is having issues running as it does the same thing (Project name is [Shulker](https://github.com/destruc7i0n/shulker) ) as the project currently using the bot.

In case it is something with the mod and not the bot I've included the output in the console, my panel cuts off some lines.
```
15.02 21:23:19 [Server] JDA MainWS-ReadThread/INFO Connected to WebSocket
15.02 21:23:19 [Server] JDA MainWS-WriteThread/ERROR WebSocket connection was closed and cannot be recovered due to identification issues
15.02 21:23:19 [Server] INFO CloseCode[DISALLOWED_INTENTS](code=4014, meaning=Disallowed intents. Your bot might not be eligible to request a privileged intent such as GUILD_PRESENCES, MESSAGE_CONTENT, or GUILD_MEMBERS.)
15.02 21:23:19 [Server] main/ERROR Failed to start the minecraft server
15.02 21:23:19 [Server] INFO java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'discord'!
15.02 21:23:19 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.11.jar:?]
15.02 21:23:19 [Server] INFO at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.11.jar:?]
15.02 21:23:19 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.11.jar:?]
15.02 21:23:19 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.11.jar:?]
15.02 21:23:19 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.11.jar:?]
15.02 21:23:19 [Server] INFO at net.minecraft.server.Main.main(Main.java:102) ~[server-intermediary.jar:?]
15.02 21:23:19 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.11.jar:?]
15.02 21:23:19 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.11.jar:?]
15.02 21:23:19 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.11.jar:?]
15.02 21:23:19 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.11.jar:?]
15.02 21:23:19 [Server] INFO at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric.jar:0.11.1]
15.02 21:23:19 [Server] INFO Caused by: java.lang.IllegalStateException: Was shutdown trying to await status.
15.02 21:23:19 [Server] INFO Reason: You tried turning on an intent you aren't allowed to use. For more information check https://jda.wiki/using-jda/troubleshooting/#im-getting-closecode4014-disallowed-intents
15.02 21:23:19 [Server] INFO at net.dv8tion.jda.internal.JDAImpl.awaitStatus(JDAImpl.java:491) ~[net_dv8tion_jda-5.0.0-beta.1-7e29d93f32b0dcfc.jar:?]
15.02 21:23:19 [Server] INFO at net.dv8tion.jda.api.JDA.awaitStatus(JDA.java:328) ~[net_dv8tion_jda-5.0.0-beta.1-7e29d93f32b0dcfc.jar:?]
15.02 21:23:19 [Server] INFO at net.dv8tion.jda.api.JDA.awaitReady(JDA.java:378) ~[net_dv8tion_jda-5.0.0-beta.1-7e29d93f32b0dcfc.jar:?]
15.02 21:23:19 [Server] INFO at net.hkva.discord.DiscordBot.connect(DiscordBot.java:34) ~[fabric-discord-integration-1.2.2.jar:?]
15.02 21:23:19 [Server] INFO at net.hkva.discord.DiscordIntegrationMod.onInitializeServer(DiscordIntegrationMod.java:70) ~[fabric-discord-integration-1.2.2.jar:?]
15.02 21:23:19 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.11.jar:?]
15.02 21:23:19 [Server] INFO ... 8 more
```

**Comment by hkva** [comment]
That last error should be fixed by enabling the "message content" intent for your Discord bot.

https://discord.com/developers/applications

![image](https://user-images.githubusercontent.com/91440203/219258864-28a767b3-7f0d-441f-8f6e-b0a134cfa57a.png)
